project:
  type: website

website:
  title: "Physics webR Lab Manual"
  site-url: https://phys-ken.github.io/web_r_for_physics
  page-navigation: true
  navbar:
    left:
      - href: index.qmd
        text: はじめに
      - href: snippets.qmd
        text: スニペット集

format:
  html:
    lang: ja
    theme: cosmo
    toc: true
    code-copy: true
    css: styles.css
